<a href="https://colab.research.google.com/github/Somrat390/Pytorch/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


# Scaler Tensor

In [ ]:
v = torch.tensor(7)
v

tensor(7)

In [ ]:
v.ndim

0

In [ ]:
v.item()

7

#Vector

In [ ]:
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

# Matrix

In [ ]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix.shape

torch.Size([2, 2])

# Tensor

In [ ]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR1 = torch.tensor([[[[3,4,5],
                          [4,5,6]]]])

In [ ]:
TENSOR1.shape

torch.Size([1, 1, 2, 3])

# Random Tensor

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8279, 0.4216, 0.2169, 0.8028],
        [0.7479, 0.2317, 0.5237, 0.4246],
        [0.4622, 0.2704, 0.1015, 0.2906]])

In [ ]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.7871, 0.9070, 0.4408, 0.0362],
         [0.8120, 0.5391, 0.6583, 0.3007],
         [0.2603, 0.4437, 0.7180, 0.3058]],

        [[0.3834, 0.2340, 0.3407, 0.1615],
         [0.5117, 0.9786, 0.1045, 0.2190],
         [0.1959, 0.6309, 0.3083, 0.7833]]])

In [ ]:
random_image_tesnor = torch.rand(size=(3,224,224))

In [ ]:
random_image_tesnor.shape

torch.Size([3, 224, 224])

In [ ]:
random_image_tesnor.ndim

3

# Zeros and ones

In [ ]:
zero = torch.zeros(size=(3,4))

In [ ]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Creating a range of tensor and tensors-like

In [ ]:
oen_to9 = torch.arange(0,10)

In [ ]:
torch.arange(0,10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
ten_zeros = torch.zeros_like(oen_to9)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor DataType

In [3]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False)



In [4]:
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0'), torch.float32)

In [5]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [6]:
int32_tensor = torch.tensor([3,6,7], dtype=torch.int32)

In [7]:
float_16_tensor * int32_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [10]:
float_16 = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16,
                               )

In [11]:
float_16 * int32_tensor

tensor([ 9., 36., 63.], dtype=torch.float16)

# Getting information from tensor

In [13]:
float_16.dtype, float_16.shape, float_16.device

(torch.float16, torch.Size([3]), device(type='cpu'))

# Manipulating Tensor

## Addition

In [14]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

## Multiply

In [15]:
tensor * 10

tensor([10, 20, 30])

## Substraction

In [16]:
tensor - 10

tensor([-9, -8, -7])

## Inbuild func

In [18]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [19]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Divison

In [20]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

# Matrix Multiplication or dot product

## Element - wise

In [22]:
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [23]:
torch.matmul(tensor,tensor)

tensor(14)

In [24]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.65 ms, sys: 89 µs, total: 1.73 ms
Wall time: 2.93 ms


In [26]:
%%time
print(torch.matmul(tensor,tensor))

tensor(14)
CPU times: user 969 µs, sys: 0 ns, total: 969 µs
Wall time: 1.04 ms


# Rules of matrix multiplication
* inner dimention have to be same.
* resulting matrix in outer shape dimention

In [27]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [28]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.8926, 0.9872],
        [0.7498, 0.3679]])

# One of the most shape error in deep learning

In [31]:
# shape for matrix multiplication
tesnor_A = torch.tensor([[1,2],
                        [2,3],
                        [5,6]])
tesnor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tesnor_A,tesnor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [32]:
tesnor_A.shape, tesnor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# To fix out tensfor shape issue, we can manipulate the shape of any of our tensor using transpose

In [34]:
tesnor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [35]:
tesnor_B.T.shape

torch.Size([2, 3])

In [38]:
tesnor_A.shape, tesnor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [36]:
torch.mm(tesnor_A,tesnor_B.T)

tensor([[ 27,  30,  33],
        [ 44,  49,  54],
        [ 95, 106, 117]])

# Find the max,min,mean,sum etc(tensor aggregation)

In [43]:
x = torch.arange(1,100,10)
x,  x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [49]:
torch.max(x), torch.min(x), x.max(), x.min()

(tensor(91), tensor(1), tensor(91), tensor(1))

In [45]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [46]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [47]:
x.type(torch.float32).mean()

tensor(46.)

In [48]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Positional Min, max argmin and argmax

In [51]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [54]:
x[9]

tensor(91)

# Reshaping, stacking, squeeing and unsqueezing

squeez - remove all 1 dimention from a tensor
insqueex -add 1 dimention

In [55]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
x_resahped = x.reshape(1,9)
x_resahped, x_resahped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
x_resahped = x.reshape(3,9)
x_resahped, x_resahped.shape

RuntimeError: shape '[3, 9]' is invalid for input of size 9

In [58]:
x_resahped = x.reshape(9,1)
x_resahped, x_resahped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [66]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [60]:
x_resahped = x.reshape(2,5)
x_resahped, x_resahped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

## change the view

In [67]:
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [68]:
# Changing z changes x (beause a view of a tensor shares the same memory as the original oen)
z[:,0]= 5
z , x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

# Stack tensor on top of each other

In [73]:
# v stacked
x_stacked = torch.stack([x,x,x,x],dim=0)

In [72]:
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [74]:
# h stacked
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

squezz = remove all single dimention from the tensor

In [76]:
x_resahped

tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 5.,  7.,  8.,  9., 10.]])

In [77]:
x.shape

torch.Size([10])

In [78]:
z

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [79]:
z.shape

torch.Size([1, 10])

In [83]:
x = z.squeeze()
x

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [81]:
z.squeeze().shape

torch.Size([10])

# unsquezz add single dimention to a target tensor

In [86]:
x.unsqueeze(dim=0)

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [87]:
x.unsqueeze(dim=1)

tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [90]:
x = torch.rand(size=(3,4))
x, x.shape

(tensor([[0.1485, 0.9288, 0.0636, 0.3825],
         [0.9636, 0.8542, 0.1711, 0.1888],
         [0.1252, 0.9707, 0.7947, 0.7762]]),
 torch.Size([3, 4]))

In [91]:
x.squeeze(), x.squeeze().shape

(tensor([[0.1485, 0.9288, 0.0636, 0.3825],
         [0.9636, 0.8542, 0.1711, 0.1888],
         [0.1252, 0.9707, 0.7947, 0.7762]]),
 torch.Size([3, 4]))

In [93]:
x.unsqueeze(dim=0), x.unsqueeze(dim=0).shape

(tensor([[[0.1485, 0.9288, 0.0636, 0.3825],
          [0.9636, 0.8542, 0.1711, 0.1888],
          [0.1252, 0.9707, 0.7947, 0.7762]]]),
 torch.Size([1, 3, 4]))

# torch.permute rearrange the demiensions of a target tensor

In [94]:
x_original  = torch.rand(size=(224,224,3))

In [95]:
x_original

tensor([[[0.4338, 0.9302, 0.5288],
         [0.4005, 0.1263, 0.2337],
         [0.6032, 0.7613, 0.3592],
         ...,
         [0.7950, 0.9013, 0.2707],
         [0.3348, 0.9534, 0.9252],
         [0.0479, 0.7270, 0.3651]],

        [[0.0886, 0.6923, 0.5509],
         [0.9791, 0.6159, 0.3081],
         [0.2335, 0.5823, 0.8529],
         ...,
         [0.8659, 0.3787, 0.7959],
         [0.6280, 0.9975, 0.2770],
         [0.2708, 0.6912, 0.1007]],

        [[0.7439, 0.2055, 0.8529],
         [0.2343, 0.6015, 0.9856],
         [0.1785, 0.8185, 0.8382],
         ...,
         [0.2267, 0.2926, 0.1951],
         [0.1365, 0.8370, 0.5269],
         [0.0310, 0.2679, 0.8832]],

        ...,

        [[0.1865, 0.4804, 0.2338],
         [0.5712, 0.8647, 0.7172],
         [0.3611, 0.4470, 0.4937],
         ...,
         [0.3691, 0.1164, 0.9248],
         [0.8217, 0.7424, 0.7432],
         [0.7949, 0.3001, 0.8355]],

        [[0.8222, 0.2476, 0.4976],
         [0.2402, 0.8641, 0.7994],
         [0.

In [97]:
x_original.permute(2, 0 ,1).shape

torch.Size([3, 224, 224])

# Indexing(select data from tensors)

In [98]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [99]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [100]:
x[0][0]

tensor([1, 2, 3])

In [101]:
x[0][0][0]

tensor(1)

In [102]:
x[1][0][0]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [103]:
x[0][2][2]

tensor(9)

In [104]:
x[:,0]

tensor([[1, 2, 3]])

In [105]:
x[:,:,1]

tensor([[2, 5, 8]])

In [106]:
x[:,1,1]

tensor([5])

In [107]:
x[:,:,2]

tensor([[3, 6, 9]])

# Pytorch tensors and numpy

In [109]:
# numpy array to tensor

import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [112]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [113]:
#change the value of the array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [115]:
# tensor to numpy
tensor = torch.ones(7)
nupy_tesnor = tensor.numpy()
tensor, nupy_tesnor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibiity(trying to take random out of random)

In [116]:
torch.rand(3,3)

tensor([[0.4270, 0.9093, 0.5097],
        [0.5813, 0.4803, 0.3398],
        [0.0261, 0.9013, 0.3365]])

In [117]:
torch.rand(3,3)

tensor([[0.8708, 0.0679, 0.8105],
        [0.4915, 0.2155, 0.5781],
        [0.0813, 0.6274, 0.6759]])

## to reduce this randomness the concept random_seed came

In [118]:
torch.rand(3,3)

tensor([[0.3266, 0.9416, 0.3405],
        [0.8614, 0.2266, 0.7227],
        [0.1181, 0.0259, 0.9330]])

In [119]:
random_tesor1 = torch.rand(3,4)
random_tesor2 = torch.rand(3,4)

In [120]:
random_tesor1, random_tesor2

(tensor([[0.7126, 0.3206, 0.8793, 0.7044],
         [0.6474, 0.5924, 0.8498, 0.7418],
         [0.2698, 0.7670, 0.7969, 0.8772]]),
 tensor([[0.2343, 0.1874, 0.4585, 0.9256],
         [0.5927, 0.5961, 0.2275, 0.5725],
         [0.5262, 0.1474, 0.0584, 0.7461]]))

In [121]:
random_tesor1 == random_tesor2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [124]:
random_seed = 32
torch.manual_seed(random_seed)
random_tesor1 = torch.rand(3,4)

random_tesor2 =random_tesor1

In [125]:
random_tesor1 == random_tesor2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [126]:
random_tesor1 = torch.rand(3,4)

# Running Tesor in GPU & Accessing GPU

In [127]:
# Getting a GPU


In [128]:
!nvidia-smi

Sun Sep 20 13:45:14 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   64C    P0             31W /   70W |     123MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----