<a href="https://colab.research.google.com/github/Somrat390/Pytorch/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


# Scaler Tensor

In [2]:
v = torch.tensor(7)
v

tensor(7)

In [3]:
v.ndim

0

In [4]:
v.item()

7

#Vector

In [5]:
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

# Matrix

In [8]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix.shape

torch.Size([2, 2])

# Tensor

In [12]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR1 = torch.tensor([[[[3,4,5],
                          [4,5,6]]]])

In [17]:
TENSOR1.shape

torch.Size([1, 1, 2, 3])

# Random Tensor

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8279, 0.4216, 0.2169, 0.8028],
        [0.7479, 0.2317, 0.5237, 0.4246],
        [0.4622, 0.2704, 0.1015, 0.2906]])

In [19]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.7871, 0.9070, 0.4408, 0.0362],
         [0.8120, 0.5391, 0.6583, 0.3007],
         [0.2603, 0.4437, 0.7180, 0.3058]],

        [[0.3834, 0.2340, 0.3407, 0.1615],
         [0.5117, 0.9786, 0.1045, 0.2190],
         [0.1959, 0.6309, 0.3083, 0.7833]]])

In [21]:
random_image_tesnor = torch.rand(size=(3,224,224))

In [22]:
random_image_tesnor.shape

torch.Size([3, 224, 224])

In [23]:
random_image_tesnor.ndim

3

# Zeros and ones

In [24]:
zero = torch.zeros(size=(3,4))

In [25]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

# Creating a range of tensor and tensors-like

In [30]:
oen_to9 = torch.arange(0,10)

In [29]:
torch.arange(0,10, 2)

tensor([0, 2, 4, 6, 8])

In [31]:
ten_zeros = torch.zeros_like(oen_to9)

In [32]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor DataType

In [37]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False)



In [38]:
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0'), torch.float32)

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16